name: vote
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/vote.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bot: '>=0.25.3'
  bot_web: '>=0.21.0'
dev_dependencies:
  bot_test: '>=0.1.5'
  browser: '>=0.9.0 <0.10.0'
  hop: '>=0.28.1+2'
  unittest: '>=0.9.0 <0.10.0'
