name: vote
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/vote.dart
environment:
  sdk: '>=0.5.3'
dependencies:
  bot_web: '>=0.20.1'
  bot: '>=0.20.1'
dev_dependencies:
  hop: '>=0.22.1+1'
