name: vote.dart
dependencies:
  unittest:
    sdk: unittest
  bot:
    git:
      url: https://github.com/kevmoo/bot.dart.git
      ref: v0.5.0
  hop:
    git:
      url: https://github.com/kevmoo/hop.dart.git
      ref: v0.2.0
