name: vote
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/vote.dart
environment:
  sdk: '>=0.6.9'
dependencies:
  bot: '>=0.23.0'
  bot_web: '>=0.20.4'
dev_dependencies:
  bot_test: '>=0.1.0'
  hop: '>=0.24.1'
